
An exception was thrown at 2024-05-29 12:56:56 :
< Something went wrong with server connection. Please try again later! >

se.kth.iv1350.exceptions.DatabaseFailureException: Something went wrong with server connection. Please try again later!
	at se.kth.iv1350.integration.InventorySystem.getItemInfo(InventorySystem.java:35)
	at se.kth.iv1350.controller.Controller.registerItem(Controller.java:65)
	at se.kth.iv1350.view.View.simulateFakeSaleStory(View.java:55)
	at se.kth.iv1350.startup.Startup.main(Startup.java:38)

An exception was thrown at 2024-05-29 12:56:56 :
< Item with item ID 6 not found! >

se.kth.iv1350.exceptions.ItemNotFoundException: Item with item ID 6 not found!
	at se.kth.iv1350.integration.InventorySystem.getItemInfo(InventorySystem.java:42)
	at se.kth.iv1350.controller.Controller.registerItem(Controller.java:65)
	at se.kth.iv1350.view.View.simulateFakeSaleStory(View.java:63)
	at se.kth.iv1350.startup.Startup.main(Startup.java:38)
